version: '3.8'

services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb_container
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./initdb:/docker-entrypoint-initdb.d
    ports:
      - '3306:3306'
    healthcheck:
      test: [ "CMD", "healthcheck.sh", "--su-mysql", "--connect", "--innodb_initialized" ]
      start_period: 1m
      start_interval: 10s
      interval: 1m
      timeout: 5s
      retries: 3

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_container
    environment:
      PMA_HOST: mariadb
      PMA_USER: user
      PMA_PASSWORD: password
      PMA_PORT: 3306
    ports:
      - '8080:80'
    depends_on:
      - mariadb

  front:
    build:
      context: ./front
      dockerfile: dockerfile
    ports:
      - '8090:3009'
    depends_on:
      mariadb:
        condition: service_healthy

  back:
    build:
      context: ./back
      dockerfile: dockerfile
    ports:
      - '5000:5000'
    env_file:
      - ./back/.env
    depends_on:
      mariadb:
        condition: service_healthy

volumes:
  mariadb_data:
